import { WorkspaceRole } from '@prisma/client';

export const PERMISSIONS = {
  MANAGE_WORKSPACE: 'MANAGE_WORKSPACE',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_MEMBERS: 'MANAGE_MEMBERS',
  REGENERATE_INVITE: 'REGENERATE_INVITE',
  MANAGE_CHANNELS: 'MANAGE_CHANNELS',
  VIEW_PRIVATE_CHANNELS: 'VIEW_PRIVATE_CHANNELS',
  SEND_MESSAGES: 'SEND_MESSAGES',
  DELETE_OWN_MESSAGES: 'DELETE_OWN_MESSAGES',
  DELETE_ANY_MESSAGE: 'DELETE_ANY_MESSAGE',
  CREATE_POST: 'CREATE_POST',
  EDIT_ANY_POST: 'EDIT_ANY_POST',
  DELETE_ANY_POST: 'DELETE_ANY_POST',
  PIN_POST: 'PIN_POST',
  DELETE_ANY_COMMENT: 'DELETE_ANY_COMMENT',
  CREATE_TASK: 'CREATE_TASK',
  ASSIGN_TASK: 'ASSIGN_TASK',
  DELETE_ANY_TASK: 'DELETE_ANY_TASK',
  USE_AI: 'USE_AI',
  MENTION_ROLE: 'MENTION_ROLE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_VALUES = Object.values(PERMISSIONS) as Permission[];

export const BUILT_IN_ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  [WorkspaceRole.OWNER]: [...PERMISSION_VALUES],
  [WorkspaceRole.ADMIN]: [
    PERMISSIONS.MANAGE_WORKSPACE,
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.MANAGE_CHANNELS,
    PERMISSIONS.VIEW_PRIVATE_CHANNELS,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.DELETE_OWN_MESSAGES,
    PERMISSIONS.DELETE_ANY_MESSAGE,
    PERMISSIONS.CREATE_POST,
    PERMISSIONS.EDIT_ANY_POST,
    PERMISSIONS.DELETE_ANY_POST,
    PERMISSIONS.PIN_POST,
    PERMISSIONS.DELETE_ANY_COMMENT,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.DELETE_ANY_TASK,
    PERMISSIONS.USE_AI,
    PERMISSIONS.MENTION_ROLE,
  ],
  [WorkspaceRole.MODERATOR]: [
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.DELETE_OWN_MESSAGES,
    PERMISSIONS.DELETE_ANY_MESSAGE,
    PERMISSIONS.CREATE_POST,
    PERMISSIONS.EDIT_ANY_POST,
    PERMISSIONS.PIN_POST,
    PERMISSIONS.DELETE_ANY_COMMENT,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.USE_AI,
    PERMISSIONS.MENTION_ROLE,
  ],
  [WorkspaceRole.MEMBER]: [
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.DELETE_OWN_MESSAGES,
    PERMISSIONS.CREATE_POST,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.USE_AI,
  ],
};

export const isPermission = (value: string): value is Permission =>
  PERMISSION_VALUES.includes(value as Permission);
